config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :lineitems
    resources :statements

    root to: "statements#index"
  end

  get 'pages/starter'
  get 'pages/blank'

  resources :statements
  resources :lineitems

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'statements#index', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'pages#blank'
  end
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  belongs_to :statement
end

app/models/statement.rb
class Statement < ActiveRecord::Base
  has_many :lineitems
  accepts_nested_attributes_for :lineitems, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/lineitems_controller.rb
module Admin
  class LineitemsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Lineitem.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Lineitem.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/statements_controller.rb
module Admin
  class StatementsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Statement.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Statement.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  attr_accessor :description, :amount 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def starter
  end

  def blank
  end

  def homepage
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def index
    @statement = Statement.all
  end

  def new
    @statement = Statement.new
    @statement.lineitems.build
    @default_line_items = [ "Opening Balance",
                            "Rent",
                            "Water",
                            "Sewerage",
                            "Refuse",
                            "VAT",
                            "Rent Recieved",
                            "Muncipal Recieved",
                            "Closing Balance",
                            "Collection Commission",
                            "Rates Payover",
                            "Payment to Owner"]
  end

  def create
    @statement = Statement.new(statement_params)
    if @statement.save
      redirect_to @statement
    else
      render action: "new"
    end
  end

  def show
  end

  def destroy
    @statement.destroy
    redirect_to statements_url
  end

  def edit
    @default_line_items = []
  end

  def update
    if @statement.update_attributes(statement_params)
      redirect_to @statement
    else
      render action: "edit"
    end
  end

  def set_statement
    @statement = Statement.find(params[:id])
  end
  private

  def statement_params
    params.require(:statement).permit(:name, :description, lineitems_attributes: [:id, :description, :amount, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/porfolio_helper.rb
module PorfolioHelper
end

app/views/layouts/_control_sidebar.html.erb
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active">
            <a href="#control-sidebar-home-tab" data-toggle="tab">
                <i class="fa fa-home"></i>
            </a>
        </li>
        <li>
            <a href="#control-sidebar-settings-tab" data-toggle="tab">
                <i class="fa fa-gears"></i>
            </a>
        </li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">
                                Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">
                                70%
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">
                    General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2015
        <a href="#">Company</a>.</strong>
    All rights reserved.
</footer>

app/views/layouts/_main_sidebar.html.erb
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <%= image_tag("user2-160x160.jpg", class: "img-circle") %>
                <!-- <img src="dist/img/user2-160x160.jpg"
  class="img-circle" alt="User Image"> -->
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <!-- Status -->
                <a href="#">
                    <i class="fa fa-circle text-success"></i>
                    Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">Navigation</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active">
                    <i class="fa fa-link"></i>
                    <%= link_to 'Statements', statements_url %>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-link"></i>
                    <span>Another Link</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-link"></i>
                    <span>Multilevel</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="#">Link in level 2</a>
                    </li>
                    <li>
                        <a href="#">Link in level 2</a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

app/views/layouts/_top_navbar.html.erb
<nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- Messages: style can be found in dropdown.less-->
            <li class="dropdown messages-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-envelope-o"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 4 messages</li>
                    <li>
                        <!-- inner menu: contains the messages -->
                        <ul class="menu">
                            <li>
                                <!-- start message -->
                                <a href="#">
                                    <div class="pull-left">
                                        <!-- User Image -->
                                        <%= image_tag("user2-160x160.jpg", class: "img-circle") %>

                                    </div>
                                    <!-- Message title and timestamp -->
                                    <h4>
                                        Support Team
                                        <small>
                                            <i class="fa fa-clock-o"></i>
                                            5 mins</small>
                                    </h4>
                                    <!-- The message -->
                                    <p>Why not buy a new awesome theme?</p>
                                </a>
                            </li>
                            <!-- end message -->
                        </ul>
                        <!-- /.menu -->
                    </li>
                    <li class="footer">
                        <a href="#">See All Messages</a>
                    </li>
                </ul>
            </li>
            <!-- /.messages-menu -->

            <!-- Notifications Menu -->
            <li class="dropdown notifications-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                    <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 10 notifications</li>
                    <li>
                        <!-- Inner Menu: contains the notifications -->
                        <ul class="menu">
                            <li>
                                <!-- start notification -->
                                <a href="#">
                                    <i class="fa fa-users text-aqua"></i>
                                    5 new members joined today
                                </a>
                            </li>
                            <!-- end notification -->
                        </ul>
                    </li>
                    <li class="footer">
                        <a href="#">View all</a>
                    </li>
                </ul>
            </li>
            <!-- Tasks Menu -->
            <li class="dropdown tasks-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-flag-o"></i>
                    <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 9 tasks</li>
                    <li>
                        <!-- Inner menu: contains the tasks -->
                        <ul class="menu">
                            <li>
                                <!-- Task item -->
                                <a href="#">
                                    <!-- Task title and progress text -->
                                    <h3>
                                        Design some buttons
                                        <small class="pull-right">20%</small>
                                    </h3>
                                    <!-- The progress bar -->
                                    <div class="progress xs">
                                        <!-- Change the css width attribute to simulate progress -->
                                        <div class="progress-bar progress-bar-aqua"
                                        style="width: 20%"
                                        role="progressbar"
                                        aria-valuenow="20"
                                        aria-valuemin="0"
                                        aria-valuemax="100">
                                            <span class="sr-only">
                                              20% Complete
                                            </span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <!-- end task item -->
                        </ul>
                    </li>
                    <li class="footer">
                        <a href="#">View all tasks</a>
                    </li>
                </ul>
            </li>
            <!-- User Account Menu -->
            <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <!-- The user image in the navbar-->
                    <%= image_tag("user2-160x160.jpg", class: "user-image") %>
                    <!-- <img src="dist/img/user2-160x160.jpg"
  class="user-image" alt="User Image"> -->
                    <!-- hidden-xs hides the username on small
  devices so only the image appears. -->
                    <span class="hidden-xs">Alexander Pierce</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- The user image in the menu -->
                    <li class="user-header">
                        <%= image_tag("user2-160x160.jpg", class: "img-circle") %>
                        <!-- <img src="dist/img/user2-160x160.jpg"
    class="img-circle" alt="User Image"> -->

                        <p>
                            Alexander Pierce - Web Developer
                            <small>Member since Nov. 2012</small>
                        </p>
                    </li>
                    <!-- Menu Body -->
                    <li class="user-body">
                        <div class="row">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </div>
                        <!-- /.row -->
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a href="#" class="btn btn-default btn-flat">Sign out</a>
                        </div>
                    </li>
                </ul>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <li>
                <a href="#" data-toggle="control-sidebar">
                    <i class="fa fa-gears"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminDash</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  </head>
  <body class="hold-transition skin-green sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a href="index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">
            <b>P-</b>DSH</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">
            <b>pro</b>DASH</span>
        </a>

        <!-- Header Navbar -->
        <%= render "layouts/top_navbar" %>
        <!-- Left side column. contains the logo and sidebar -->
        <%= render "layouts/main_sidebar" %>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <section class="content-header">
            <h1>
              Rental Dashboard
              <small>Control Panel</small>
            </h1>
            <ol class="breadcrumb">
              <li>
                <a href="#">
                  <i class="fa fa-dashboard"></i>
                  Level</a>
              </li>
              <li class="active">Dashboard</li>
            </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div id="navbar">
              <ul class="nav navbar-nav pull-right">
                <% if signed_in? %>
                  <li><span><%= current_user.email %></span></li>
                  <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Sign in', sign_in_path %></li>
                <% end %>
              </ul>
            </div>

            <%= yield %>

          </section>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Main Footer -->
        <%= render "layouts/footer" %>
        <!-- Control Sidebar -->
        <%= render "layouts/control_sidebar" %>
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
          immediately after the control sidebar -->
          <div class="control-sidebar-bg"></div>
    </div>
  </body>
</html>

</html>

app/views/lineitems/index.html.erb
<%= @lineitem.all %>

app/views/pages/homepage.html.erb
<%= link_to 'Add New Data', new_statement_path %>

app/views/pages/starter.html.erb
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">
                    <b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">
                    <b>Admin</b>LTE</span>
            </a>

            <!-- Header Navbar -->
            <%= render "layouts/top_navbar" %>
            <!-- Left side column. contains the logo and sidebar -->
            <%= render "layouts/main_sidebar" %>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Rental Dashboard
                        <small>Optional description</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <a href="#">
                                <i class="fa fa-dashboard"></i>
                                Level</a>
                        </li>
                        <li class="active">Here</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <%= yield %>

                </section>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->

            <!-- Main Footer -->
            <%= render "layouts/footer" %>
            <!-- Control Sidebar -->
            <%= render "layouts/control_sidebar" %>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
        </div>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    </body>
</html>

app/views/porfolio/new.html.erb
<%= simple_for_for @statement do |f| %>
  <%= f.input :month %>
  <%= f.association :building %>
  <%= f.association :property %>
  <%= f.association :tenant %>
  <%= f.input :opening_balance %>
  <%= f.input :rent %>
  <%= f.input :water %>
  <%= f.input :refuse %>
  <%= f.input :sewerage %>
  <%= f.input :vat %>
  <%= f.input :water_recieved %>
  <%= f.input :rent_recieved %>
  <%= f.input :closing_balance %>
  <%= f.input :commission %>
  <%= f.input :rates_paid %>
  <%= f.input :payment_for_owner %>
  <%= f.button :submit %>
<%= end %>

app/views/statements/_fixed_lineitem_fields.html.haml
- @default_line_items.each do |default_values|
 = f.simple_fields_for :lineitems do |f|
  .nested-fields
   = f.input :description, :input_html => { :value => default_values }
   = f.input :amount

app/views/statements/_form.html.haml
= simple_form_for @statement do |f|
  = f.error_notification
  = f.input :name
  = f.input :description
  %h3 Line Items
  .lineitem
    = render'/statements/fixed_lineitem_fields',f:f
    = f.simple_fields_for :lineitems do |lineitem|
      = render '/statements/lineitem_fields', f: lineitem
    .links
      = link_to_add_association 'Add Line Item', f, :lineitems,count: 1
  = f.button :submit

app/views/statements/_lineitem_fields.html.haml
.nested-fields
 = f.input :description, placeholder: 'other'
 = f.input :amount
 = link_to_remove_association "Remove Line Item", f

app/views/statements/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @statement
= '|'
= link_to 'Back', statement_path

app/views/statements/index.html.haml
%h1 Listing of Statements
%table.table
 %thead
  %th Name
  %th Description
 %tbody
  -@statement.each do |statement|
   %tr
    %td
     = statement.name
    %td
     = statement.description
    %td
     = link_to 'Show', statement, class: 'btn btn-default btn-xs'
     = link_to 'Edit', edit_statement_path(statement),
                       class: 'btn btn-default btn-xs'
     = link_to 'Destroy', statement, :confirm => 'Are you sure?',
                                   :method => :delete,
                                   class: 'btn btn-xs btn-danger'

app/views/statements/new.html.haml
.box.box-primary
  %h3 Statement
  = render 'form'

app/views/statements/show.html.haml
%h3 Statements
%table#example2.table.table-bordered.table-hover.dataTable{"aria-describedby" => "example2_info", :role => "grid"}
  %tr
    %td Name
    %td Description
  %tr
    %td= @statement.name
    %td= @statement.description
%h3 Line Item list
%table.table.table-bordered.table-hover.dataTable{"aria-describedby" => "example2_info", :role => "grid"}
  %tr
    %td Description
    %td Amount
    - @statement.lineitems.each do |lineitem|
      %tr
        %td=lineitem.description
        %td=lineitem.amount

= link_to 'Edit', edit_statement_path(@statement)
= '|'
= link_to 'Back', statement_path